[build]
  publish = "."
  ignore = "exit 0"

[[redirects]]
  from = "/"
  to = "/expense-mobile.html"
  status = 200

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
